### ISSUE TITLE
формулы

### ISSUE THREAD

**Issue by htmls** [alhimik1986/php-excel-templator#2]
Еще вопрос появился: есть возможность использовать стандартные формулы excel?
Например, одна ячейка заполняется по шаблону, соседняя вычисляется по формуле, заданной на этапе редактирования шаблона.

**Comment by alhimik1986** [comment]
Ячейку с формулой, наверно, тоже нужно задавать шаблонной переменной, а значение (формулу) подставлять в самом коде. Пока только так.

**Comment by htmls** [comment]
Ок
