### ISSUE TITLE
Заполнение статичных данных в таблице.

### ISSUE THREAD

**Issue by chernogolov** [alhimik1986/php-excel-templator#29]
Здравствуйте! Подскажите пожалуйста, можно ли как-то заполнить статичные данные и формулы которые изначально стоят в шаблоне, чтобы они тоже протягивались вниз вместе с данными массива.

![Screenshot_57](https://user-images.githubusercontent.com/10895230/137894967-ecea00e3-2e41-4410-8598-37e2daaea6b7.png)

**Comment by alhimik1986** [comment]
Приветствую. К сожалению формулы, как и все статичные значения, не дублируются. Дублируются (растягиваются) только шаблонные переменные. То есть там, где нужно "растянуть" формулу, надо вставить так же шаблонную переменную, а в коде (в качестве значений шаблонной переменной) вставлять массив формул `['=A1+B1', '=A2+B2'].`

**Comment by chernogolov** [comment]
Благодарю! Я сделал событие, которое добавляет шаблон [! !] для формул и статичных параметров. Но возникла проблема. Для того, чтобы получить количество добавляемых строк мне пришлось, добавить $params в функцию для AFTER_INSERT_PARAMS.
 
Сделал я это естественно в папке vendor - src/PhpExcelTemplator.php 88 строка. 
Стало вот так: $events[self::AFTER_INSERT_PARAMS]($sheet, $templateVarsArr, $params); 

Может быть есть другое решение?

Вот мой код, возможно он пригодится:
````
$events = [
            PhpExcelTemplator::AFTER_INSERT_PARAMS => function(Worksheet $sheet, array $templateVarsArr, array $params) 
        {
                foreach ($templateVarsArr as $rowKey => $row) {
                    foreach ($row as $colKey => $colContent) {

                        //проверяем наличие шаблона [! !] в ячейке
                        preg_match('~\[!(.*?)!\]~', $colContent, $output);
                        if (isset($output[1])) {
                            for ($i = 0; $i < count($params['[timemark]']->value); $i++) {

                                //получаем координаты ячейки
                                $colIndex = $colKey + 1;
                                $rowIndex = $rowKey + 1;
                                $coordinate = Coordinate::stringFromColumnIndex($colIndex) . ($rowIndex + $i);

                                //если работаем с формулой, необходимо увеличить индексы иначе просто копируем значение
                                if(strpos($output[1], '=') !== false)
                                {
                                    $pattern = "/". $rowIndex ."/i";
                                    $replacement = $rowIndex + $i;
                                    $string = preg_replace($pattern, $replacement, $output[1]);
                                    $sheet->getCell($coordinate)->setValue($string);
                                }
                                else
                                    $sheet->getCell($coordinate)->setValue($output[1]);
                            }
                        }
                    }
                }
            },
        ];
````


Вот как это выглядит в шаблоне
![Screenshot_59](https://user-images.githubusercontent.com/10895230/138044678-0678737b-3273-47f7-b05c-9d359b9ac433.png)
:

**Comment by alhimik1986** [comment]
Ну нельзя же так просто взять и тупо увеличить на +1 всякое число, которое есть в ячейке, которое совпадает с `$rowIndex`. Есть же и относительные и абсолютные (ячейки, которые нельзя увеличивать), а может встретиться константа, которая может совпасть с `$rowIndex`.

Как мне кажется, автоматическое увеличение индекса ячеек в формулах - это большая задача, для которой нужно создавать целый класс (или несколько). И там нужно учитывать все нюансы, да и без багов не обойдётся. А баги в формулах (особенно редкие) - это, поверь, очень отвратительно, очень много ответственных данных могут быть в этих формулах. Поэтому такую ответственную задачу я лучше переложу на пользователя. Благо, что гибкость это позволяет сделать.

**Comment by chernogolov** [comment]
Согласен. Это очень сырое решение. Но другого я пока не нашел к сожалению. В моем частном случае это работает с горем пополам так как формулы в моем шаблоне идентичные. И не содержат ничего другого.
