### ISSUE TITLE
Изменить высоту всего ряда в зависимости от значения в ячейке

### ISSUE THREAD

**Issue by FuglyShmugly** [alhimik1986/php-excel-templator#39]
Добрый день, возможно ли такое? А то например названия товаров бывают длинные и обрезаются.

**Comment by alhimik1986** [comment]
Да. Высоту рядов можно подогнать. Это можно сделать, используя события:
https://github.com/alhimik1986/php-excel-templator#events
Например, AFTER_INSERT_PARAMS или BEFORE_SAVE.

И в одном из этих коллбэков (событий) выполнить что-то вроде:
`$sheet->getRowDimension($row_id)->setRowHeight(-1);`

Координаты ячеек с шаблонными переменными находятся в `$templateVarsArr`

**Comment by FuglyShmugly** [comment]
Спасибо большое.
