### ISSUE TITLE
Слетает объединение ячеек при вставке массива

### ISSUE THREAD

**Issue by slavabars** [alhimik1986/php-excel-templator#4]
Вот пример разметки

A | B | C | D | E
------------ | ------------- | ------------- | ------------- | -------------
[] | [] | [>] | [<] | [] 

C и D обеденены.

Если у нас больше одной строки, то все следующие строки будут разъеденные.
На выходе получим что колонка D будет пустая

A | B | C | D | E
------------ | ------------- | ------------- | ------------- | -------------
[] | [] | [>] | [<] | [] 
[] | [] | [><] |  | [] 
[] | [] | [><] |  | [] 
[] | [] | [><] |  | []

**Comment by slavabars** [comment]
Можно использовать mergeCells, но это при статичном шаблоне. При динамичном нужно сначала вычислить объедененные ячейки

**Comment by alhimik1986** [comment]
Вставлять шаблонные переменные в объединённые ячейки не рекомендуется. Т.к., естественно, будут появляться пустые ячейки.
Рекомендую объединять ячейки в стилях. В коде есть возможность изменять стили ячеек, используя функцию обратного вызова.

**Comment by alhimik1986** [comment]
Особенно, если нужно будет вставлять двумерные массивы, то вообще неразбериха получится.

**Comment by slavabars** [comment]
Ну так основные документы в большинстве случаев имеют объеденные ячейки.

**Comment by slavabars** [comment]
`    $callback = [
        '[id]' => function(alhimik1986\PhpExcelTemplator\params\CallbackParam $param) {
            $sheet = $param->sheet;
            $row_index = $param->row_index;
            $cell_coordinate = $param->coordinate;
            $amount = $param->param[$row_index];
            $amount = preg_replace('/[\s\$]/', '', $amount);
            $sheet->getStyle($cell_coordinate)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setARGB('FFB5FFA8');
            $b=preg_replace("/[^0-9]/", '', $cell_coordinate);
            $sheet->mergeCells("a".($b).":b".($b));
        },
    ];`

Объединяет так же только первый вывод, последующие не объединяет.

**Comment by alhimik1986** [comment]
Я редко с таким сталкивался. Можешь прислать пример шаблона, который доставляет с этим больше всех проблем? Я подумаю, что можно с этим сделать.

**Comment by slavabars** [comment]
Проблема в том что параметры на склейку ячеек идет до вставки в таблицу, а должно быть позже

```
		$params = static::getCorrectedParams($params, $callbacks);
		static::clearTemplateVarsInSheet($sheet, $templateVarsArr, $params);
		static::insertParams($sheet, $templateVarsArr, $params);
		return $sheet;
```

то есть я делаю код

```
        '[id]' => function(alhimik1986\PhpExcelTemplator\params\CallbackParam $param) use($id) {
            $sheet = $param->sheet;
            $cell_coordinate = $param->coordinate;
            $b=preg_replace("/[^0-9]/", '', $cell_coordinate);
            for ($cc = $b; $cc < ($b + count($id)); $cc++) {
                $sheet->mergeCells("a" . ($cc) . ":b" . ($cc));
                $sheet->mergeCells("c" . ($cc) . ":e" . ($cc));
                $sheet->mergeCells("f" . ($cc) . ":j" . ($cc));
                $sheet->mergeCells("k" . ($cc) . ":m" . ($cc));
                $sheet->mergeCells("p" . ($cc) . ":s" . ($cc));
            }
        },
```
И у меня не выходит, т.к. сначала идет объединение, а потом очистка.
А должно работать уже со вставленными параметрами

Если же я потом работаю с таблицей, после вставки, то проблем нет, но это костыль. И теряются данные после объединения.

**Comment by alhimik1986** [comment]
В общем я решил эту проблему. Для такого типа шаблонов нужен специальный сеттер, который вставляет строки, а не ячейки со сдвигом вниз; и который объединяет ячейки. Я его реализовал, но пока не публиковал. Нужно оформить документацию. Могу ли я для в качестве примера использования спец. сеттера (в папке samples) использовать твой шаблон?

**Comment by slavabars** [comment]
Да, используй.

**Comment by alhimik1986** [comment]
Спасибо. В общем я, опубликовался. Можно пользоваться)
